AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation template for S3 bucket resources needed for HUJI exercise 6.

Parameters:
  CodePackageDate:
    Description: The date of the code package in ms.
    Type: String

Resources:
  OwllearnCodeBaseS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: huji-lightricks-owllearn-code-bucket
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

Outputs:
  OwllearnCodeBaseS3BucketName:
    Description: Name of code base bucket
    Value: !Ref OwllearnCodeBaseS3Bucket
    Export:
      Name: huji-lightricks-owllearn-code-bucket-name

  OwllearnCodeBaseS3BucketArn:
    Description: ARN of code base bucket
    Value: !GetAtt OwllearnCodeBaseS3Bucket.Arn
    Export:
      Name: huji-lightricks-owllearn-code-bucket-arn
