---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Cloudformation template for resources needed for Owllearn.
Parameters:
    CodePackageDate:
        Description: The date of the code package in ms.
        Type: String
Resources:
    OwllearnDecksTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: huji-lightricks-owllearn-decks
            AttributeDefinitions:
                - AttributeName: userId
                  AttributeType: S
                - AttributeName: deckId
                  AttributeType: S
            KeySchema:
                - AttributeName: userId
                  KeyType: HASH
                - AttributeName: deckId
                  KeyType: RANGE
            BillingMode: PAY_PER_REQUEST
    OwllearnDeckPreviewsTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: huji-lightricks-owllearn-deck-previews
            AttributeDefinitions:
                - AttributeName: userId
                  AttributeType: S
                - AttributeName: deckId
                  AttributeType: S
            KeySchema:
                - AttributeName: userId
                  KeyType: HASH
                - AttributeName: deckId
                  KeyType: RANGE
            BillingMode: PAY_PER_REQUEST
    OwllearnCardsTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: huji-lightricks-owllearn-cards
            AttributeDefinitions:
                - AttributeName: deckId
                  AttributeType: S
                - AttributeName: cardId
                  AttributeType: S
            KeySchema:
                - AttributeName: deckId
                  KeyType: HASH
                - AttributeName: cardId
                  KeyType: RANGE
            BillingMode: PAY_PER_REQUEST
    OwllearnDecksGetRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: huji-lightricks-owllearn-decks-get-role
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - lambda.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
            Policies:
                - PolicyName: huji-lightricks-owllearn-decks-get-policy
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Action:
                                - dynamodb:GetItem
                                - dynamodb:Query
                            Resource: !GetAtt OwllearnDecksTable.Arn
    OwllearnDecksEditRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: huji-lightricks-owllearn-decks-edit-role
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - lambda.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
            Policies:
                - PolicyName: huji-lightricks-owllearn-decks-edit-policy
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Action:
                                - dynamodb:GetItem
                                - dynamodb:PutItem
                            Resource:
                                - !GetAtt OwllearnDecksTable.Arn
                          - Effect: Allow
                            Action:
                                - dynamodb:GetItem
                                - dynamodb:PutItem
                            Resource:
                                - !GetAtt OwllearnDeckPreviewsTable.Arn
                          - Effect: Allow
                            Action:
                                - dynamodb:GetItem
                                - dynamodb:DeleteItem
                                - dynamodb:PutItem
                                - dynamodb:BatchWriteItem
                            Resource:
                                - !GetAtt OwllearnCardsTable.Arn

    OwllearnDecksCreateRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: huji-lightricks-owllearn-decks-create-role
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - lambda.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
            Policies:
                - PolicyName: huji-lightricks-owllearn-decks-create-policy
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Action:
                                - dynamodb:PutItem
                            Resource:
                                - !GetAtt OwllearnDecksTable.Arn
                          - Effect: Allow
                            Action:
                                - dynamodb:PutItem
                            Resource:
                                - !GetAtt OwllearnDeckPreviewsTable.Arn
    OwllearnDecksDeleteRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: huji-lightricks-owllearn-decks-delete-role
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - lambda.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
            Policies:
                - PolicyName: huji-lightricks-owllearn-decks-delete-policy
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Action:
                                - dynamodb:DeleteItem
                                - dynamodb:GetItem
                            Resource:
                                - !GetAtt OwllearnDecksTable.Arn
                          - Effect: Allow
                            Action:
                                - dynamodb:DeleteItem
                                - dynamodb:GetItem
                            Resource:
                                - !GetAtt OwllearnDeckPreviewsTable.Arn
                          - Effect: Allow
                            Action:
                                - dynamodb:DeleteItem
                                - dynamodb:GetItem
                                - dynamodb:BatchWriteItem
                                - dynamodb:Query
                            Resource:
                                - !GetAtt OwllearnCardsTable.Arn

    OwllearnDeckPreviewsEditRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: huji-lightricks-owllearn-deck-previews-edit-role
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - lambda.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
            Policies:
                - PolicyName: huji-lightricks-owllearn-deck-previews-edit-policy
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Action:
                                - dynamodb:UpdateItem
                            Resource:
                                - !GetAtt OwllearnDeckPreviewsTable.Arn

    OwllearnDeckPreviewsGetRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: huji-lightricks-owllearn-deck-previews-get-role
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - lambda.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
            Policies:
                - PolicyName: huji-lightricks-owllearn-deck-previews-get-policy
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Action:
                                - dynamodb:GetItem
                                - dynamodb:Query
                            Resource:
                                - !GetAtt OwllearnDeckPreviewsTable.Arn

    OwllearnDeckPreviewsGetLambdaFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: huji-lightricks-owllearn-deck-previews-get-lambda
            Handler: lambdas.deck_previews_get.handler
            Role: !GetAtt OwllearnDeckPreviewsGetRole.Arn
            Timeout: 10
            CodeUri:
                Bucket: huji-lightricks-owllearn-code-bucket
                Key: !Sub Owllearn-${CodePackageDate}-code-package.zip
            Runtime: python3.8

    OwllearnDecksGetLambdaFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: huji-lightricks-owllearn-decks-get-lambda
            Handler: lambdas.decks_get.handler
            Role: !GetAtt OwllearnDecksGetRole.Arn
            Timeout: 10
            CodeUri:
                Bucket: huji-lightricks-owllearn-code-bucket
                Key: !Sub Owllearn-${CodePackageDate}-code-package.zip
            Runtime: python3.8
    OwllearnDecksEditLambdaFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: huji-lightricks-owllearn-decks-edit-lambda
            Handler: lambdas.decks_edit.handler
            Role: !GetAtt OwllearnDecksEditRole.Arn
            Timeout: 10
            CodeUri:
                Bucket: huji-lightricks-owllearn-code-bucket
                Key: !Sub Owllearn-${CodePackageDate}-code-package.zip
            Runtime: python3.8
    OwllearnDecksCreateLambdaFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: huji-lightricks-owllearn-decks-create-lambda
            Handler: lambdas.decks_create.handler
            Role: !GetAtt OwllearnDecksCreateRole.Arn
            Timeout: 10
            CodeUri:
                Bucket: huji-lightricks-owllearn-code-bucket
                Key: !Sub Owllearn-${CodePackageDate}-code-package.zip
            Runtime: python3.8
    OwllearnDecksDeleteLambdaFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: huji-lightricks-owllearn-decks-delete-lambda
            Handler: lambdas.decks_delete.handler
            Role: !GetAtt OwllearnDecksDeleteRole.Arn
            Timeout: 10
            CodeUri:
                Bucket: huji-lightricks-owllearn-code-bucket
                Key: !Sub Owllearn-${CodePackageDate}-code-package.zip
            Runtime: python3.8

    OwllearnDeckPreviewsEditLambdaFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: huji-lightricks-owllearn-deck-previews-edit-lambda
            Handler: lambdas.deck_previews_edit.handler
            Role: !GetAtt OwllearnDeckPreviewsEditRole.Arn
            Timeout: 10
            CodeUri:
                Bucket: huji-lightricks-owllearn-code-bucket
                Key: !Sub Owllearn-${CodePackageDate}-code-package.zip
            Runtime: python3.8

    OwllearnRestAPI:
        Type: AWS::ApiGateway::RestApi
        Properties:
            Name: Owllearn-Api
            Description: owllearn rest api

    OwllearnDecksApiResource:
        Type: AWS::ApiGateway::Resource
        Properties:
            RestApiId: !Ref OwllearnRestAPI
            ParentId: !GetAtt OwllearnRestAPI.RootResourceId
            PathPart: decks

    OwllearnDeckPreviewsApiResource:
        Type: AWS::ApiGateway::Resource
        Properties:
            RestApiId: !Ref OwllearnRestAPI
            ParentId: !GetAtt OwllearnRestAPI.RootResourceId
            PathPart: deck-previews


    OwllearnGetDecksMethod:
        Type: AWS::ApiGateway::Method
        Properties:
            AuthorizationType: NONE
            HttpMethod: GET
            Integration:
                IntegrationHttpMethod: POST
                Type: AWS_PROXY
                Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OwllearnDecksGetLambdaFunction.Arn}/invocations"
            ResourceId: !Ref OwllearnDecksApiResource
            RestApiId: !Ref OwllearnRestAPI

    OwllearnDeleteDecksMethod:
        Type: AWS::ApiGateway::Method
        Properties:
            AuthorizationType: NONE
            HttpMethod: DELETE
            Integration:
                IntegrationHttpMethod: POST
                Type: AWS_PROXY
                Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OwllearnDecksDeleteLambdaFunction.Arn}/invocations"
            ResourceId: !Ref OwllearnDecksApiResource
            RestApiId: !Ref OwllearnRestAPI
    OwllearnCreateDecksMethod:
        Type: AWS::ApiGateway::Method
        Properties:
            AuthorizationType: NONE
            HttpMethod: POST
            Integration:
                IntegrationHttpMethod: POST
                Type: AWS_PROXY
                Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OwllearnDecksCreateLambdaFunction.Arn}/invocations"
            ResourceId: !Ref OwllearnDecksApiResource
            RestApiId: !Ref OwllearnRestAPI
    OwllearnEditDecksMethod:
        Type: AWS::ApiGateway::Method
        Properties:
            AuthorizationType: NONE
            HttpMethod: PUT
            Integration:
                IntegrationHttpMethod: POST
                Type: AWS_PROXY
                Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OwllearnDecksEditLambdaFunction.Arn}/invocations"
            ResourceId: !Ref OwllearnDecksApiResource
            RestApiId: !Ref OwllearnRestAPI

    OwllearnEditDeckPreviewsMethod:
        Type: AWS::ApiGateway::Method
        Properties:
            AuthorizationType: NONE
            HttpMethod: PUT
            Integration:
                IntegrationHttpMethod: POST
                Type: AWS_PROXY
                Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OwllearnDeckPreviewsEditLambdaFunction.Arn}/invocations"
            ResourceId: !Ref OwllearnDeckPreviewsApiResource
            RestApiId: !Ref OwllearnRestAPI

    OwllearnGetDeckPreviewsMethod:
        Type: AWS::ApiGateway::Method
        Properties:
            AuthorizationType: NONE
            HttpMethod: GET
            Integration:
                IntegrationHttpMethod: POST
                Type: AWS_PROXY
                Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OwllearnDeckPreviewsGetLambdaFunction.Arn}/invocations"
            ResourceId: !Ref OwllearnDeckPreviewsApiResource
            RestApiId: !Ref OwllearnRestAPI

    OwllearnLambdaInvokePermissionDecksGet:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !GetAtt OwllearnDecksGetLambdaFunction.Arn
            Principal: apigateway.amazonaws.com
    OwllearnLambdaInvokePermissionDecksCreate:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !GetAtt OwllearnDecksCreateLambdaFunction.Arn
            Principal: apigateway.amazonaws.com
    OwllearnLambdaInvokePermissionDecksEdit:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !GetAtt OwllearnDecksEditLambdaFunction.Arn
            Principal: apigateway.amazonaws.com
    OwllearnLambdaInvokePermissionDecksDelete:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !GetAtt OwllearnDecksDeleteLambdaFunction.Arn
            Principal: apigateway.amazonaws.com

    OwllearnLambdaInvokePermissionDeckPreviewsEdit:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !GetAtt OwllearnDeckPreviewsEditLambdaFunction.Arn
            Principal: apigateway.amazonaws.com

    OwllearnLambdaInvokePermissionDeckPreviewsGet:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !GetAtt OwllearnDeckPreviewsGetLambdaFunction.Arn
            Principal: apigateway.amazonaws.com

    OwllearnApiDeployment:
        Type: AWS::ApiGateway::Deployment
        DependsOn:
            - OwllearnGetDecksMethod
            - OwllearnDeleteDecksMethod
            - OwllearnCreateDecksMethod
            - OwllearnEditDecksMethod
            - OwllearnEditDeckPreviewsMethod
            - OwllearnGetDeckPreviewsMethod
        Properties:
            RestApiId: !Ref OwllearnRestAPI

    OwllearnApiStage:
        Type: AWS::ApiGateway::Stage
        Properties:
            DeploymentId: !Ref OwllearnApiDeployment
            RestApiId: !Ref OwllearnRestAPI
            StageName: prod
